22:19:34,727 bot_logger DEBUG Bot started
22:19:36,795 bot_logger DEBUG Category list was sent at show_categories()
22:19:38,503 bot_logger DEBUG show_items_in_categories
22:19:38,512 bot_logger DEBUG Filters data updated with catkey
22:19:38,514 bot_logger DEBUG Item Куртка retrieved
22:19:38,514 bot_logger ERROR <class 'AttributeError'> at show_item()
22:19:38,514 bot_logger ERROR 'str' object has no attribute 'unwrap'
Traceback (most recent call last):
  File "C:\Учёба\Питон\бот дежавю\Dejavu-bot\handlers.py", line 85, in show_item
    media = build_media_group(item.GetImagePaths())
  File "C:\Учёба\Питон\бот дежавю\Dejavu-bot\Models.py", line 65, in GetImagePaths
    for im in query:
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\peewee.py", line 4588, in next
    self.cursor_wrapper.iterate()
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\peewee.py", line 4505, in iterate
    self.initialize()  # Lazy initialization.
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\peewee.py", line 7675, in _initialize_columns
    node = raw_node.unwrap()
AttributeError: 'str' object has no attribute 'unwrap'
22:21:04,996 bot_logger DEBUG Bot started
22:21:06,285 bot_logger DEBUG Category list was sent at show_categories()
22:21:07,596 bot_logger DEBUG show_items_in_categories
22:21:07,601 bot_logger DEBUG Filters data updated with catkey
22:21:07,604 bot_logger DEBUG Item Куртка retrieved
22:21:07,604 bot_logger ERROR <class 'AttributeError'> at show_item()
22:21:07,604 bot_logger ERROR module 'aiogram.types' has no attribute 'MediaGroup'
Traceback (most recent call last):
  File "C:\Учёба\Питон\бот дежавю\Dejavu-bot\handlers.py", line 85, in show_item
    media = build_media_group(item.GetImagePaths())
  File "C:\Учёба\Питон\бот дежавю\Dejavu-bot\utils.py", line 6, in build_media_group
    images = types.MediaGroup()
AttributeError: module 'aiogram.types' has no attribute 'MediaGroup'
22:27:01,637 bot_logger DEBUG Bot started
22:27:03,397 bot_logger DEBUG Category list was sent at show_categories()
22:27:04,580 bot_logger DEBUG show_items_in_categories
22:27:04,589 bot_logger DEBUG Filters data updated with catkey
22:27:04,590 bot_logger DEBUG Item Куртка retrieved
22:27:04,590 bot_logger ERROR <class 'AttributeError'> at show_item(): type object 'list' has no attribute 'attach_photo'
22:29:42,320 bot_logger DEBUG Bot started
22:29:44,134 bot_logger DEBUG Category list was sent at show_categories()
22:29:45,390 bot_logger DEBUG show_items_in_categories
22:29:45,398 bot_logger DEBUG Filters data updated with catkey
22:29:45,400 bot_logger DEBUG Item Куртка retrieved
22:29:45,401 bot_logger ERROR <class 'TypeError'> at show_item(): Can't instantiate abstract class InputFile with abstract method read
22:34:03,54 bot_logger DEBUG Bot started
22:34:06,541 bot_logger DEBUG Category list was sent at show_categories()
22:34:07,702 bot_logger DEBUG show_items_in_categories
22:34:07,709 bot_logger DEBUG Filters data updated with catkey
22:34:07,711 bot_logger DEBUG Item Куртка retrieved
22:34:07,711 bot_logger ERROR <class 'TypeError'> at show_item(): descriptor 'append' for 'list' objects doesn't apply to a 'FSInputFile' object
22:35:55,766 bot_logger DEBUG Bot started
22:35:57,29 bot_logger DEBUG Category list was sent at show_categories()
22:35:58,471 bot_logger DEBUG show_items_in_categories
22:35:58,479 bot_logger DEBUG Filters data updated with catkey
22:35:58,480 bot_logger DEBUG Item Куртка retrieved
22:35:58,481 bot_logger ERROR <class 'TypeError'> at show_item(): build_item_kb() missing 1 required positional argument: 'position'
22:38:27,728 bot_logger DEBUG Bot started
22:38:29,74 bot_logger DEBUG Category list was sent at show_categories()
22:38:30,155 bot_logger DEBUG show_items_in_categories
22:38:30,163 bot_logger DEBUG Filters data updated with catkey
22:38:30,165 bot_logger DEBUG Item Куртка retrieved
22:38:30,165 bot_logger ERROR <class 'TypeError'> at show_item(): BaseModel.__init__() takes 1 positional argument but 2 were given
22:39:41,983 bot_logger DEBUG show_items_in_categories
22:39:41,990 bot_logger DEBUG Filters data updated with catkey
22:39:41,992 bot_logger DEBUG Item Куртка retrieved
22:39:41,992 bot_logger ERROR <class 'TypeError'> at show_item(): BaseModel.__init__() takes 1 positional argument but 2 were given
22:42:21,356 bot_logger DEBUG Bot started
22:42:24,21 bot_logger DEBUG Category list was sent at show_categories()
22:42:25,844 bot_logger DEBUG show_items_in_categories
22:42:25,850 bot_logger DEBUG Filters data updated with catkey
22:42:25,851 bot_logger DEBUG Item Куртка retrieved
22:42:25,852 bot_logger ERROR <class 'TypeError'> at show_item(): BaseModel.__init__() takes 1 positional argument but 2 were given
22:46:39,935 bot_logger DEBUG Bot started
22:46:41,339 bot_logger DEBUG Category list was sent at show_categories()
22:46:43,345 bot_logger DEBUG show_items_in_categories
22:46:43,354 bot_logger DEBUG Filters data updated with catkey | (469492126, 1)
22:46:43,357 bot_logger DEBUG Item Куртка retrieved
22:46:43,357 bot_logger ERROR <class 'TypeError'> at show_item(): BaseModel.__init__() takes 1 positional argument but 2 were given
22:46:59,310 bot_logger DEBUG show_items_in_categories
22:46:59,321 bot_logger DEBUG Filters data updated with catkey | (469492126, 3)
22:46:59,323 bot_logger DEBUG Item Куртка retrieved
22:46:59,324 bot_logger ERROR <class 'TypeError'> at show_item(): BaseModel.__init__() takes 1 positional argument but 2 were given
22:52:16,118 bot_logger DEBUG show_items_in_categories
22:52:16,126 bot_logger DEBUG Filters data updated with catkey | (469492126, 1)
22:52:16,128 bot_logger DEBUG Item Куртка retrieved
22:52:16,129 bot_logger ERROR <class 'TypeError'> at show_item(): BaseModel.__init__() takes 1 positional argument but 2 were given
22:54:29,877 bot_logger DEBUG Bot started
22:54:32,60 bot_logger DEBUG Category list was sent at show_categories()
22:54:32,896 bot_logger DEBUG show_items_in_categories
22:54:32,902 bot_logger DEBUG Filters data updated with catkey | (469492126, 1)
22:54:32,905 bot_logger DEBUG Preferences: (469492126, 1)
22:54:32,906 bot_logger DEBUG Item Куртка retrieved
22:54:32,906 bot_logger ERROR <class 'TypeError'> at show_item(): BaseModel.__init__() takes 1 positional argument but 2 were given
22:55:22,107 bot_logger DEBUG show_items_in_categories
22:55:22,113 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
22:55:22,114 bot_logger DEBUG Preferences: (469492126, 2)
22:55:22,115 bot_logger DEBUG Item Куртка retrieved
22:55:22,115 bot_logger ERROR <class 'TypeError'> at show_item(): BaseModel.__init__() takes 1 positional argument but 2 were given
22:56:41,916 bot_logger DEBUG Bot started
22:56:43,40 bot_logger DEBUG Category list was sent at show_categories()
22:56:44,89 bot_logger DEBUG show_items_in_categories
22:56:44,98 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
22:56:44,98 bot_logger DEBUG Preferences: (469492126, 2)
22:56:44,99 bot_logger DEBUG Item Куртка retrieved
22:56:44,99 bot_logger ERROR <class 'TypeError'> at show_item(): BaseModel.__init__() takes 1 positional argument but 2 were given
22:57:10,383 bot_logger DEBUG show_items_in_categories
22:57:10,390 bot_logger DEBUG Filters data updated with catkey | (469492126, 1)
22:57:10,391 bot_logger DEBUG Preferences: (469492126, 1)
22:57:10,391 bot_logger DEBUG Item Куртка retrieved
22:57:10,392 bot_logger ERROR <class 'TypeError'> at show_item(): BaseModel.__init__() takes 1 positional argument but 2 were given
23:00:28,241 bot_logger DEBUG Bot started
23:00:29,763 bot_logger DEBUG Category list was sent at show_categories()
23:00:30,995 bot_logger DEBUG show_items_in_categories
23:00:31,1 bot_logger DEBUG Filters data updated with catkey | (469492126, 1)
23:00:31,2 bot_logger DEBUG Preferences: (469492126, 1)
23:00:31,298 bot_logger DEBUG No matching rows
23:00:34,219 bot_logger DEBUG Category list was sent at show_categories()
23:00:35,714 bot_logger DEBUG show_items_in_categories
23:00:35,721 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
23:00:35,722 bot_logger DEBUG Preferences: (469492126, 2)
23:00:35,723 bot_logger DEBUG Item Куртка retrieved
23:00:35,723 bot_logger ERROR <class 'TypeError'> at show_item(): BaseModel.__init__() takes 1 positional argument but 2 were given
23:02:51,771 bot_logger DEBUG Bot started
23:02:53,558 bot_logger DEBUG Category list was sent at show_categories()
23:02:54,543 bot_logger DEBUG show_items_in_categories
23:02:54,552 bot_logger DEBUG Filters data updated with catkey | (469492126, 3)
23:02:54,553 bot_logger DEBUG Preferences: (469492126, 3)
23:02:54,707 bot_logger DEBUG No matching rows
23:02:57,691 bot_logger DEBUG Category list was sent at show_categories()
23:02:58,730 bot_logger DEBUG show_items_in_categories
23:02:58,736 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
23:02:58,737 bot_logger DEBUG Preferences: (469492126, 2)
23:02:58,737 bot_logger DEBUG Item Куртка | кожанка retrieved
23:02:58,738 bot_logger ERROR <class 'TypeError'> at show_item(): list.count() takes exactly one argument (0 given)
23:04:05,64 bot_logger DEBUG Bot started
23:04:06,317 bot_logger DEBUG Category list was sent at show_categories()
23:04:07,689 bot_logger DEBUG show_items_in_categories
23:04:07,698 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
23:04:07,699 bot_logger DEBUG Preferences: (469492126, 2)
23:04:07,699 bot_logger DEBUG Item Куртка | кожанка retrieved
23:04:07,700 bot_logger DEBUG Media built: 1
23:04:07,700 bot_logger ERROR <class 'TypeError'> at show_item(): BaseModel.__init__() takes 1 positional argument but 2 were given
23:06:31,373 bot_logger DEBUG Bot started
23:06:33,283 bot_logger DEBUG Category list was sent at show_categories()
23:06:35,7 bot_logger DEBUG show_items_in_categories
23:06:35,15 bot_logger DEBUG Filters data updated with catkey | (469492126, 1)
23:06:35,16 bot_logger DEBUG Preferences: (469492126, 1)
23:06:35,164 bot_logger DEBUG No matching rows
23:06:36,442 bot_logger DEBUG show_items_in_categories
23:06:36,453 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
23:06:36,453 bot_logger DEBUG Preferences: (469492126, 2)
23:06:36,453 bot_logger DEBUG Item Куртка | кожанка retrieved
23:06:36,454 bot_logger DEBUG Media built: 1
23:06:36,454 bot_logger ERROR <class 'TypeError'> at show_item(): BaseModel.__init__() takes 1 positional argument but 2 were given
23:08:49,353 bot_logger DEBUG Bot started
23:08:51,919 bot_logger DEBUG Category list was sent at show_categories()
23:08:53,289 bot_logger DEBUG show_items_in_categories
23:08:53,295 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
23:08:53,296 bot_logger DEBUG Preferences: (469492126, 2)
23:08:53,297 bot_logger DEBUG Item Куртка | кожанка retrieved
23:08:53,298 bot_logger DEBUG Media built: 1
23:08:53,299 bot_logger ERROR <class 'TypeError'> at show_item(): BaseModel.__init__() takes 1 positional argument but 2 were given
23:09:58,711 bot_logger DEBUG Bot started
23:09:59,670 bot_logger DEBUG Category list was sent at show_categories()
23:10:00,866 bot_logger DEBUG show_items_in_categories
23:10:00,874 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
23:10:00,875 bot_logger DEBUG Preferences: (469492126, 2)
23:10:00,877 bot_logger DEBUG Item Куртка | кожанка retrieved
23:10:00,877 bot_logger DEBUG Media built: 1
23:10:00,878 bot_logger ERROR <class 'AttributeError'> at show_item(): module 'secrets' has no attribute 'token_urlsafe'
23:12:52,330 bot_logger DEBUG Bot started
23:12:53,837 bot_logger DEBUG Category list was sent at show_categories()
23:12:55,152 bot_logger DEBUG show_items_in_categories
23:12:55,160 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
23:12:55,161 bot_logger DEBUG Preferences: (469492126, 2)
23:12:55,162 bot_logger DEBUG Item Куртка | кожанка retrieved
23:12:55,162 bot_logger DEBUG Media built: 1
23:12:55,166 bot_logger ERROR <class 'pydantic_core._pydantic_core.ValidationError'> at show_item(): 4 validation errors for SendMediaGroup
media.0.InputMediaAudio
  Input should be a valid dictionary or instance of InputMediaAudio [type=model_type, input_value=<aiogram.types.input_file...t at 0x00000230849BB730>, input_type=FSInputFile]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
media.0.InputMediaDocument
  Input should be a valid dictionary or instance of InputMediaDocument [type=model_type, input_value=<aiogram.types.input_file...t at 0x00000230849BB730>, input_type=FSInputFile]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
media.0.InputMediaPhoto
  Input should be a valid dictionary or instance of InputMediaPhoto [type=model_type, input_value=<aiogram.types.input_file...t at 0x00000230849BB730>, input_type=FSInputFile]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
media.0.InputMediaVideo
  Input should be a valid dictionary or instance of InputMediaVideo [type=model_type, input_value=<aiogram.types.input_file...t at 0x00000230849BB730>, input_type=FSInputFile]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
23:17:08,860 bot_logger DEBUG Bot started
23:17:10,672 bot_logger DEBUG Category list was sent at show_categories()
23:17:11,551 bot_logger DEBUG show_items_in_categories
23:17:11,559 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
23:17:11,560 bot_logger DEBUG Preferences: (469492126, 2)
23:17:11,561 bot_logger DEBUG Item Куртка | кожанка retrieved
23:17:11,562 bot_logger DEBUG Media built: 1
23:18:23,131 bot_logger DEBUG Bot started
23:18:24,583 bot_logger DEBUG Category list was sent at show_categories()
23:18:25,470 bot_logger DEBUG show_items_in_categories
23:18:25,478 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
23:18:25,479 bot_logger DEBUG Preferences: (469492126, 2)
23:18:25,479 bot_logger DEBUG Item Куртка | кожанка retrieved
23:18:25,480 bot_logger DEBUG Media built: 1
23:18:25,480 bot_logger ERROR <class 'AttributeError'> at show_item(): module 'secrets' has no attribute 'token_urlsafe'
23:28:32,28 bot_logger DEBUG Bot started
23:28:33,587 bot_logger DEBUG Category list was sent at show_categories()
23:28:34,631 bot_logger DEBUG show_items_in_categories
23:28:34,639 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
23:28:34,640 bot_logger DEBUG Preferences: (469492126, 2)
23:28:34,641 bot_logger DEBUG Item Куртка | кожанка retrieved
23:28:34,642 bot_logger DEBUG Media built: 1
23:28:34,642 bot_logger ERROR <class 'TypeError'> at show_item(): BaseModel.__init__() takes 1 positional argument but 2 were given
23:29:03,288 bot_logger DEBUG Bot started
23:29:04,664 bot_logger DEBUG Category list was sent at show_categories()
23:29:05,425 bot_logger DEBUG show_items_in_categories
23:29:05,432 bot_logger DEBUG Filters data updated with catkey | (469492126, 1)
23:29:05,433 bot_logger DEBUG Preferences: (469492126, 1)
23:29:05,632 bot_logger DEBUG No matching rows
23:29:06,917 bot_logger DEBUG show_items_in_categories
23:29:06,925 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
23:29:06,925 bot_logger DEBUG Preferences: (469492126, 2)
23:29:06,926 bot_logger DEBUG Item Куртка | кожанка retrieved
23:29:06,926 bot_logger DEBUG Media built: 1
23:29:06,927 bot_logger ERROR <class 'TypeError'> at show_item(): BaseModel.__init__() takes 1 positional argument but 2 were given
23:29:32,286 bot_logger DEBUG Bot started
23:29:33,332 bot_logger DEBUG Category list was sent at show_categories()
23:29:34,389 bot_logger DEBUG show_items_in_categories
23:29:34,398 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
23:29:34,399 bot_logger DEBUG Preferences: (469492126, 2)
23:29:34,400 bot_logger DEBUG Item Куртка | кожанка retrieved
23:29:34,400 bot_logger DEBUG Media built: 1
23:29:49,938 bot_logger DEBUG show_items_in_categories
23:29:49,944 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
23:29:49,944 bot_logger DEBUG Preferences: (469492126, 2)
23:29:49,945 bot_logger DEBUG Item Куртка | кожанка retrieved
23:29:49,947 bot_logger DEBUG Media built: 1
23:29:59,979 bot_logger DEBUG Bot started
23:30:01,310 bot_logger DEBUG Category list was sent at show_categories()
23:30:02,237 bot_logger DEBUG show_items_in_categories
23:30:02,243 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
23:30:02,244 bot_logger DEBUG Preferences: (469492126, 2)
23:30:02,245 bot_logger DEBUG Item Куртка | кожанка retrieved
23:30:02,245 bot_logger DEBUG Media built: 1
23:31:54,149 bot_logger DEBUG Bot started
23:31:55,756 bot_logger DEBUG Category list was sent at show_categories()
23:31:57,969 bot_logger DEBUG show_items_in_categories
23:31:57,976 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
23:31:57,976 bot_logger DEBUG Preferences: (469492126, 2)
23:31:57,977 bot_logger DEBUG Item Куртка | кожанка retrieved
23:31:57,977 bot_logger DEBUG Media built: 1
23:31:57,978 bot_logger ERROR <class 'TypeError'> at show_item(): BaseModel.__init__() takes 1 positional argument but 2 were given
23:32:18,747 bot_logger DEBUG Bot started
23:32:19,890 bot_logger DEBUG Category list was sent at show_categories()
23:32:20,859 bot_logger DEBUG show_items_in_categories
23:32:20,866 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
23:32:20,866 bot_logger DEBUG Preferences: (469492126, 2)
23:32:20,867 bot_logger DEBUG Item Куртка | кожанка retrieved
23:32:20,868 bot_logger DEBUG Media built: 1
23:40:23,576 bot_logger DEBUG Bot started
23:40:25,602 bot_logger DEBUG Category list was sent at show_categories()
23:40:26,778 bot_logger DEBUG show_items_in_categories
23:40:26,784 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
23:40:26,785 bot_logger DEBUG Preferences: (469492126, 2)
23:40:26,786 bot_logger DEBUG Item Куртка | кожанка retrieved
23:40:26,786 bot_logger DEBUG Media built: 1
23:40:26,786 bot_logger ERROR <class 'TypeError'> at show_item(): KeyboardBuilder.button() takes 1 positional argument but 3 were given
23:42:10,118 bot_logger DEBUG Bot started
23:42:11,205 bot_logger DEBUG Category list was sent at show_categories()
23:42:12,269 bot_logger DEBUG show_items_in_categories
23:42:12,277 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
23:42:12,278 bot_logger DEBUG Preferences: (469492126, 2)
23:42:12,279 bot_logger DEBUG Item Куртка | кожанка retrieved
23:42:12,280 bot_logger DEBUG Media built: 1
23:45:25,531 bot_logger DEBUG Bot started
23:45:39,701 bot_logger DEBUG Category list was sent at show_categories()
23:45:43,719 bot_logger DEBUG show_items_in_categories
23:45:43,727 bot_logger DEBUG Filters data updated with catkey | (469492126, 1)
23:45:43,729 bot_logger DEBUG Preferences: (469492126, 1)
23:45:44,42 bot_logger DEBUG No matching rows
23:45:46,885 bot_logger DEBUG show_items_in_categories
23:45:46,892 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
23:45:46,893 bot_logger DEBUG Preferences: (469492126, 2)
23:45:46,894 bot_logger DEBUG Item Куртка | кожанка retrieved
23:45:46,894 bot_logger DEBUG Media built: 1
23:53:49,460 bot_logger DEBUG Bot started
23:54:33,621 bot_logger DEBUG Bot started
23:54:41,875 bot_logger DEBUG Category list was sent at show_categories()
23:54:43,405 bot_logger DEBUG show_items_in_categories
23:54:43,413 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
23:54:43,414 bot_logger DEBUG Preferences: (469492126, 2)
23:54:43,415 bot_logger DEBUG Item Куртка | кожанка retrieved
23:54:43,415 bot_logger DEBUG Media built: 1
00:00:04,449 bot_logger DEBUG Bot started
00:00:09,245 bot_logger DEBUG Category list was sent at show_categories()
00:00:12,359 bot_logger DEBUG show_items_in_categories
00:00:12,367 bot_logger DEBUG Filters data updated with catkey | (968324872, 2)
00:00:12,367 bot_logger DEBUG Preferences: (968324872, 2)
00:00:12,368 bot_logger DEBUG Item Куртка | кожанка retrieved
00:00:12,368 bot_logger DEBUG Media built: 1
00:00:18,451 aiogram.event ERROR Cause exception while process update id=100184959 by bot id=6350909967
ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.3/v/string_type
Traceback (most recent call last):
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 308, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 157, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 275, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
  File "C:\Учёба\Питон\бот дежавю\Dejavu-bot\handlers.py", line 97, in default
    await clbck.message.answer(clbck.message.text)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\types\message.py", line 1725, in answer
    return SendMessage(
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic\main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.3/v/string_type
00:00:21,811 aiogram.event ERROR Cause exception while process update id=100184960 by bot id=6350909967
ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.3/v/string_type
Traceback (most recent call last):
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 308, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 157, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 275, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
  File "C:\Учёба\Питон\бот дежавю\Dejavu-bot\handlers.py", line 97, in default
    await clbck.message.answer(clbck.message.text)
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\types\message.py", line 1725, in answer
    return SendMessage(
  File "C:\Users\Пользователь\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic\main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.3/v/string_type
00:00:24,932 bot_logger DEBUG show_items_in_categories
00:00:24,937 bot_logger DEBUG Filters data updated with catkey | (968324872, 3)
00:00:24,937 bot_logger DEBUG Preferences: (968324872, 3)
00:00:25,197 bot_logger DEBUG No matching rows
01:35:41,12 aiogram.dispatcher ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
15:26:08,418 bot_logger DEBUG Bot started
15:26:19,279 bot_logger DEBUG Category list was sent at show_categories()
15:26:23,65 bot_logger DEBUG show_items_in_categories
15:26:23,71 bot_logger DEBUG Filters data updated with catkey | (604362551, 1)
15:26:23,71 bot_logger DEBUG Preferences: (604362551, 1)
15:26:23,230 bot_logger DEBUG No matching rows
15:26:26,115 bot_logger DEBUG Category list was sent at show_categories()
15:26:27,883 bot_logger DEBUG show_items_in_categories
15:26:27,892 bot_logger DEBUG Filters data updated with catkey | (604362551, 2)
15:26:27,892 bot_logger DEBUG Preferences: (604362551, 2)
15:26:27,893 bot_logger DEBUG Item Куртка | кожанка retrieved
15:26:27,893 bot_logger DEBUG Media built: 1
23:07:26,684 bot_logger DEBUG Bot started
23:08:02,224 bot_logger DEBUG Category list was sent at show_categories()
23:08:03,734 bot_logger DEBUG show_items_in_categories
23:08:03,741 bot_logger DEBUG Filters data updated with catkey | (469492126, 1)
23:08:03,741 bot_logger DEBUG Preferences: (469492126, 1)
23:08:03,870 bot_logger DEBUG No matching rows
23:08:06,178 bot_logger DEBUG show_items_in_categories
23:08:06,182 bot_logger DEBUG Filters data updated with catkey | (469492126, 2)
23:08:06,183 bot_logger DEBUG Preferences: (469492126, 2)
23:08:06,185 bot_logger DEBUG Item Куртка | кожанка retrieved
23:08:06,185 bot_logger DEBUG Media built: 1
